language: rust
install:
    - sudo apt-get update
    - sudo apt-get install libpam0g-dev libgtk-3-dev
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: kWRcECQY6H/4ckG5A5ss4zbnzTRzbz9p6wQNFpMmL8WE1yEq/Dysdxp9JALSRGVsTe3qwDTbP1GiVAci8GkCPfpDk5qDcvGIM5ePJArWw8omitlu4QhRUG6oZmsm3Z0F01XwbT8rhIjjqp06+kiQ4d45VpkK2mIPVTP9FFvo5DU=
notifications:
  email:
    on_success: never
