language: rust
rust:
  - nightly

sudo: false
addons:
  apt:
    packages:
      - libpam0g-dev
      - libgtk-3-dev

script:
  - cargo build --release --verbose
  - cargo test --verbose


notifications:
  email:
    on_success: never
