language: rust
install: sudo apt-get install libpam0g-dev libgtk-3-dev
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: esVMgmgebMrNf4P3LQsq9kLoZ0T0lZkFCNvB+CN4cVw9fkaAw19RaqPLfsJtOGFfe6j9Co+4xuT4LgpKoED3dG1/oYl2Dl+vifZMgw05EF4lLgDVOnbFoBpVxp7OekQgrPc2PBExfNoROBLfKoOfC4W/cdbWuynXmyrNGBK10Ds=
notifications:
  email:
    on_success: never
