[package]

name = "rdm"
version = "0.0.1"
authors = ["Florian Wilkens <mrfloya_github@outlook.com>"]
description = "Simple Display Manager inspired by SLiM"
repository = "https://github.com/mrfloya/rdm"
readme = "README.md"
license = "MIT"

[profile.release]
debug-assertions = false
lto = true

[features]
debug = []

[dependencies]
log = "0.3.4"
env_logger = "0.3.2"

[dependencies.dbus]
version = "0.3.4"

[dependencies.pam-auth]
version = "0.3.0"

[dependencies.gtk]
version = "0.1.0"
features = ["v3_10"]

[dependencies.gdk]
version = "0.5.0"

[dependencies.gdk-pixbuf]
version = "0.1.0"
