[package]

name = "rdm"
version = "0.0.1"
authors = ["Florian Wilkens <mrfloya_github@outlook.com>"]
description = "Simple Display Manager inspired by SLiM"
repository = "https://github.com/mrfloya/rdm"
readme = "README.md"
license = "MIT"

[profile.release]
lto = true

[dependencies]
pam-auth = "*"

[dependencies.gtk]
version = "*"
features = ["gtk_3_10"]

[dependencies.gdk]
version = "*"
features = ["gdk_3_10"]
