[package]
name = "rdmcommon"
version = "0.0.1"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
description = "Common library for rdm"
repository = "https://github.com/1wilkens/rdm"
readme = "README.md"
license = "MIT"

[dependencies]
log = "0.3.6"
