[package]
name = "rdmcommon"
version = "0.0.1"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
description = "Common library for rdm"
repository = "https://github.com/1wilkens/rdm"
readme = "README.md"
license = "MIT"

[dependencies]
log = "0.3.6"

bytes = "0.4.4"
futures = "0.1.14"
tokio-core = "0.1.2"
tokio-io = "0.1.2"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"